name: Porto Dental
favicon: null
layout_spectrum: 0.4208699055016041
typography_spectrum: 0.6527204874437302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#aa5938'
    - '#c39685'
    - '#edb29d'
    - '#c07258'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.3828854563180357
  rhythmicContrast: 0.25
purpose: []
